/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  docs: [
    {
      type: "doc",
      label: "Introduction",
      id: "intro",
    },
    {
      type: "category",
      collapsed: false,
      label: "Getting Started",
      items: [
        {
          type: "doc",
          label: "Installation",
          id: "getting-started/installation",
        },
        {
          type: "doc",
          label: "Segment Server",
          id: "getting-started/segment-server",
        },
        {
          type: "doc",
          label: "Segment CLI",
          id: "getting-started/segment-cli",
        },
        {
          type: "doc",
          label: "Command Reference",
          id: "getting-started/command-reference",
        },
      ],
    },
    {
      type: "category",
      collapsed: true,
      label: "Segment Internals",
      items: [
        {
          type: "doc",
          label: "Protocol",
          id: "segment-internals/protocol",
        },
      ],
    },
  ],
};

module.exports = sidebars;
